style: "github"
template: "CHANGELOG.tpl.md"
info:
    title: "CHANGELOG"
    repository_url: "https://github.com/basecodeoy/xit"
options:
    commits:
        filters:
            Type:
                - "ADDED"
                - "CHANGED"
                - "DEPRECATED"
                - "REMOVED"
                - "FIXED"
                - "SECURITY"
    commit_groups:
        title_maps:
            ADDED: "Added"
            CHANGED: "Changed"
            DEPRECATED: "Deprecated"
            REMOVED: "Removed"
            FIXED: "Fixed"
            SECURITY: "Security"
    header:
        pattern: "^(\\w*)\\:\\s(.*)$"
        pattern_maps:
            - "Type"
            - "Subject"
    notes:
        keywords:
            - "BREAKING CHANGE"
