# https://docs.github.com/en/actions

name: "Release"

on: # yamllint disable-line rule:truthy
    push:
        tags:
            - "**"

jobs:
    release:
        name: "Release"

        runs-on: "ubuntu-latest"

        timeout-minutes: 5

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4.2.2"
              with:
                  token: "${{ secrets.PAT }}"

            - name: "Create release"
              uses: "basecodeoy/.github/actions/github/release/create@1.0.1"
              with:
                  github-token: "${{ secrets.PAT }}"

            - name: "Generate executable"
              run: "chmod +x ./bin/git-chglog"

            - name: "Generate changelog"
              run: "./bin/git-chglog -o CHANGELOG.md"

            - name: "Commit"
              uses: "stefanzweifel/git-auto-commit-action@v5"
              with:
                  branch: "main"
                  commit_message: "RELEASE: Update changelog"
                  file_pattern: "CHANGELOG.md"
